# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: bust_track_development

production:
  <<: *default
  database: bust_track_development
  # database: bust_track_production

staging:
  <<: *default
  database: bust_track_staging
